## Q1: Fun with arrays

**A.**  Create the array: 
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.


**B.** Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [1]:
import numpy as np
a = np.arange(15).reshape(3,5).transpose()+1
print("a:\n", a)
b = np.zeros((2,a.shape[1]))
b[0] = a[1,:]
b[1] = a[3,:]
print("b:\n", b)
size = 10
c = np.ones((size,size))
c[1:size-1,1:size-1]=0
print("c:\n", c)

a:
 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
b:
 [[ 2.  7. 12.]
 [ 4.  9. 14.]]
c:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Q3: Are you faster than numpy?

Numpy of course has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:
$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`. Check the runtime as well.

In [2]:
import numpy as np
arr = np.arange(1000)
def std_dev(arr):
    sum = np.sum(arr) / len(arr)
    sum2 = (arr - sum)**2 / len(arr)
    return np.sqrt(sum2)

def std_np(arr):
    return np.std(arr) 

In [3]:
%timeit std_np(arr)

85.3 µs ± 7.59 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [4]:
%timeit std_dev(arr)

38.9 µs ± 6.25 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
